import localFont from 'next/font/local';
import { lora } from './google-fonts/fonts';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${lora.variable} `}>{children}</body>
		</html>
	);
}

